# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


default: &default
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  adapter: mysql2
  database: db211511
  username: db211511
  password: <%= ENV["PASSWORD"] %>
  host: 211511.db.tornado-node.net
  port: 3306

test:
  adapter: mysql2
  database: db211511
  username: db211511
  password: <%= ENV["PASSWORD"] %>
  host: 211511.db.tornado-node.net
  port: 3306

production:
  adapter: mysql2
  database: db211511
  username: db211511
  password: <%= ENV["PASSWORD"] %>
  host: 211511.db.tornado-node.net
  port: 3306


db:
  adapter: mysql2
  database: db211511
  username: db211511
  password: <%= ENV["PASSWORD"] %>
  host: 211511.db.tornado-node.net
  port: 3306



