# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


default: &default
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  adapter: mysql2
  database: wordpress
  username: root
  password: root
  host: 127.0.0.1
  port: 8889

test:
  adapter: mysql2
  database: wordpress
  username: root
  password: root
  host: 127.0.0.1
  port: 8889


production:
  adapter: mysql2
  database: wordpress
  username: root
  password: root
  host: 127.0.0.1
  port: 8889

db:
  adapter: mysql2
  database: wordpress
  username: root
  password: root
  host: 127.0.0.1
  port: 8889





