# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


default: &default
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  adapter: mysql2
  database: heroku_b53baed0fd674b6
  username: bd28859a8aa472
  password: 5591cda0
  host: mysql://bd28859a8aa472:5591cda0@eu-cdbr-west-02.cleardb.net/heroku_b53baed0fd674b6?reconnect=true

test:
  adapter: mysql2
  database: heroku_b53baed0fd674b6
  username: bd28859a8aa472
  password: 5591cda0
  host: mysql://bd28859a8aa472:5591cda0@eu-cdbr-west-02.cleardb.net/heroku_b53baed0fd674b6?reconnect=true127.0.0.1


production:
  adapter: mysql2
  database: heroku_b53baed0fd674b6
  username: bd28859a8aa472
  password: 5591cda0
  host: mysql://bd28859a8aa472:5591cda0@eu-cdbr-west-02.cleardb.net/heroku_b53baed0fd674b6?reconnect=true

db:
  adapter: mysql2
  database: heroku_b53baed0fd674b6
  username: bd28859a8aa472
  password: 5591cda0
  host: mysql://bd28859a8aa472:5591cda0@eu-cdbr-west-02.cleardb.net/heroku_b53baed0fd674b6?reconnect=true





